# Generated by Django 4.2.13 on 2024-07-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email_participant',
        ),
    ]
