# Generated by Django 3.2 on 2024-07-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_participant',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
