# Generated by Django 4.2.13 on 2024-07-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_useraccount_email_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_participant',
            field=models.EmailField(default='default@example.com', max_length=70),
        ),
    ]
