# Generated by Django 3.2 on 2024-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_participant',
            field=models.EmailField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
