# Generated by Django 4.1.3 on 2024-06-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='address',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='photo',
        ),
    ]
