# Generated by Django 4.2.13 on 2024-07-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='photo',
            field=models.ImageField(default='blank', upload_to='organization', verbose_name="Organization's Photo"),
        ),
    ]
