# Generated by Django 3.2 on 2024-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
