from django.urls import path
from databaseadmin.views import AnalyteUpdateReagentsAPIView,AnalyteAddReagentsAPIView,AnalytesReagentsAPIView,AnalyteAddReagents,AnalytesListAPIView,MethodsPostAPIView,InstrumentsPostAPIView,InstrumentTypeCreateView,UnitsListAPIView,NewsListView,InstrumentsAPIView, InstrumentsUpdateAPIView, InstrumentTypeView,AnalyteUpdateAPIView, AnalyteAPIView, MethodsAPIView, UpdateInstrumentTypeView,  MethodsUpdateAPIView, UnitsAPIView, UnitsUpdateAPIView, ActivityLogDatabaseadmin, ReagentsListAPIView, ReagentsPostAPIView, ReagentsPutAPIView ,ManufacturalListAPIView, ManufacturalPostAPIView, ManufacturalPutAPIView, SchemeAPIView, SchemePostAPIView, SchemeUpdateAPIView, SampleListView, SamplePostView

urlpatterns = [
    path('units_update/<id>', UnitsUpdateAPIView.as_view(), name='units_update'),
    path('units_create', UnitsAPIView.as_view(), name='units_create'),
    path('units_list/<id>', UnitsListAPIView.as_view(), name='units_list'),
    path('history_list/<id>', ActivityLogDatabaseadmin.as_view(), name='history_list'),
    path('reagent_update/<id>', ReagentsPutAPIView.as_view(), name='reagent_update'),
    path('reagent_create', ReagentsPostAPIView.as_view(), name='reagent_create'),
    path('reagent_list/<id>', ReagentsListAPIView.as_view(), name='reagent_list'), 
    path('manufactural_update/<id>', ManufacturalPutAPIView.as_view(), name='manufactural_update'),
    path('manufactural_create', ManufacturalPostAPIView.as_view(), name='manufactural_create'),
    path('manufactural_list/<id>', ManufacturalListAPIView.as_view(), name='manufactural_list'),
    path('instrument-type-list/<id>',InstrumentTypeView.as_view(), name='instrument-type-list'),

    path('instrument-type-create-list',InstrumentTypeCreateView.as_view(), name='instrument-type-create-list'),
    path('update-instrument-type-list/<id>',
        UpdateInstrumentTypeView.as_view(), name='update-instrument-type-list'),
    path('methods-list/<id>',
         MethodsAPIView.as_view(), name='methods-list'),
    path('methods-create-list',
         MethodsPostAPIView.as_view(), name='methods-create-list'),
    path('update-method-list/<id>',
        MethodsUpdateAPIView.as_view(), name='update-method-list'),
    path('analyte-add-reagent',
        AnalyteAddReagents.as_view(), name='analyte-add-reagent'),
    path('analyte-create-list',
        AnalyteAPIView.as_view(), name='analyte-create-list'),
    path('analyte-list/<id>',
        AnalytesListAPIView.as_view(), name='analyte-list'),
    path('update-analyte/<id>',
        AnalyteUpdateAPIView.as_view(), name='update-analyte'),
    path('instrument-list/<id>',
         InstrumentsAPIView.as_view(), name='instrument-list'),
    path('instrument-create',
         InstrumentsPostAPIView.as_view(), name='instrument-create'),     
    path('update-instrument-list/<id>',
        InstrumentsUpdateAPIView.as_view(), name='update-instrument-list'),
    path('news-list',
         NewsListView.as_view(), name='news-list'),
    path('scheme-list/<id>',
         SchemeAPIView.as_view(), name='scheme-list/<id>'),
    path('post-scheme',
        SchemePostAPIView.as_view(), name='post-scheme'),
    path('update-scheme-list',
        SchemeUpdateAPIView.as_view(), name='update-scheme-list'),    
    path('sample-list/<id>',
         SampleListView.as_view(), name='sample-list'),
    path('post-sample',
         SamplePostView.as_view(), name='post-sample'),

    #analyte adding reagents
    path('analyte-reagents-list/<id>',
         AnalytesReagentsAPIView.as_view(), name='analyte-reagents-list'),     
    path('analyte-add-reagent/<id>',
        AnalyteAddReagentsAPIView.as_view(), name='analyte-add-reagent'),
    path('analyte-update-reagent/<id>',
         AnalyteUpdateReagentsAPIView.as_view(), name='analyte-update-reagent'),

]