# Generated by Django 3.2 on 2024-07-02 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0001_initial'),
        ('registrationadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='cycle_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitylogunits',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Ready', 'Ready'), ('Open', 'Open'), ('Closed', 'Closed'), ('Report Available', 'Report Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='round',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.scheme'),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Ready', 'Ready'), ('Open', 'Open'), ('Closed', 'Closed'), ('Report Available', 'Report Available')], max_length=50),
        ),
    ]
