# Generated by Django 3.2 on 2024-09-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
