# Generated by Django 5.0.7 on 2024-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='participants',
        ),
        migrations.AddField(
            model_name='round',
            name='participants',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
