# Generated by Django 3.2 on 2024-09-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='participants',
        ),
    ]
