# Generated by Django 3.2 on 2024-07-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='labs',
            new_name='participants',
        ),
    ]
