# Generated by Django 3.2 on 2024-07-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='participants',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
