# Generated by Django 3.2 on 2024-07-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedscheme',
            options={'verbose_name': 'SelectedScheme'},
        ),
    ]
