# Generated by Django 3.2 on 2024-07-12 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '__first__'),
        ('labowner', '__first__'),
        ('databaseadmin', '0001_initial'),
        ('registrationadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Scheme added date')),
                ('lab_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab name')),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('scheme_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.scheme', verbose_name='Scheme name')),
            ],
            options={
                'verbose_name': 'Scheme',
            },
        ),
    ]
