# Generated by Django 3.2 on 2024-09-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0002_remove_round_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='participants',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
