# Generated by Django 3.2 on 2024-06-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0002_auto_20240614_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Ready', 'Ready'), ('Issued', 'Issued'), ('Open', 'Open'), ('Saved', 'Saved'), ('Submitted', 'Submitted'), ('Closed', 'Closed'), ('Report Available', 'Report Available')], default='Inactive', max_length=50),
        ),
    ]
