# Generated by Django 3.2 on 2024-08-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0002_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='cv_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='mean_result',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='median_result',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='result',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='robust_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='std_deviation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
