# Generated by Django 5.0.7 on 2024-09-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0002_remove_round_participants_round_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
