# Generated by Django 4.2.13 on 2024-07-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0003_sample_scheme_scheme_activitylogunits_scheme_id_and_more'),
        ('registrationadmin', '0002_remove_round_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.scheme'),
        ),
    ]
