# Generated by Django 3.2 on 2024-07-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0001_initial'),
        ('registrationadmin', '0002_alter_selectedscheme_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedscheme',
            options={'verbose_name': 'Scheme'},
        ),
        migrations.AlterField(
            model_name='selectedscheme',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheme added date'),
        ),
        migrations.RemoveField(
            model_name='selectedscheme',
            name='scheme_id',
        ),
        migrations.AddField(
            model_name='selectedscheme',
            name='scheme_id',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Scheme'),
        ),
    ]
