# Generated by Django 4.2.13 on 2024-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.CharField(null=True),
        ),
    ]
