# Generated by Django 3.2 on 2024-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0003_round_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='instrument_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='method_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='reagent_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='round_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='unit_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
