# Generated by Django 4.2.13 on 2024-07-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0003_round_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='scheme',
        ),
    ]
