# Generated by Django 3.2 on 2024-07-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0003_auto_20240713_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedscheme',
            options={'verbose_name': 'Selected Scheme'},
        ),
    ]
