# Generated by Django 3.2 on 2024-07-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0004_alter_selectedscheme_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='scheme',
        ),
        migrations.AddField(
            model_name='payment',
            name='scheme',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='selectedscheme',
            name='scheme_id',
        ),
        migrations.AddField(
            model_name='selectedscheme',
            name='scheme_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
