# Generated by Django 3.2 on 2024-06-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0004_round_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='cycle_no',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
