# Generated by Django 3.2 on 2024-09-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0004_auto_20240910_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='z_scores_with_robust_mean',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
