# Generated by Django 5.0.7 on 2024-09-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0002_alter_cycle_cycle'),
        ('registrationadmin', '0004_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedscheme',
            name='cycle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.cycle'),
        ),
    ]
