# Generated by Django 5.0.7 on 2024-09-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0003_merge_0002_alter_cycle_cycle_0002_auto_20240911_1632'),
        ('registrationadmin', '0005_statistics_z_scores_with_robust_mean'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cycle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.cycle'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='round',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
