# Generated by Django 3.2 on 2024-07-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '__first__'),
        ('registrationadmin', '0005_auto_20240713_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedscheme',
            name='lab_id',
        ),
        migrations.AddField(
            model_name='selectedscheme',
            name='participant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab'),
        ),
    ]
