# Generated by Django 5.0.7 on 2024-09-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0006_remove_payment_scheme_payment_cycle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedscheme',
            name='scheme_id',
        ),
    ]
