# Generated by Django 3.2 on 2024-06-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0006_auto_20240624_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='Option',
        ),
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Ready', 'Ready'), ('Issued', 'Issued'), ('Open', 'Open'), ('Saved', 'Saved'), ('Submitted', 'Submitted'), ('Closed', 'Closed'), ('Report Available', 'Report Available')], default='Inactive', max_length=50),
        ),
    ]
