# Generated by Django 5.0.7 on 2024-09-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0006_payment_cycle_id_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedscheme',
            options={},
        ),
    ]
