# Generated by Django 3.2 on 2024-06-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0007_auto_20240624_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylogunits',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Ready', 'Ready'), ('Issued', 'Issued'), ('Open', 'Open'), ('Saved', 'Saved'), ('Submitted', 'Submitted'), ('Closed', 'Closed'), ('Report Available', 'Report Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Ready', 'Ready'), ('Issued', 'Issued'), ('Open', 'Open'), ('Saved', 'Saved'), ('Submitted', 'Submitted'), ('Closed', 'Closed'), ('Report Available', 'Report Available')], max_length=50),
        ),
    ]
