# Generated by Django 5.0.7 on 2024-09-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0007_alter_selectedscheme_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='cycle_no',
            new_name='cycle_id',
        ),
    ]
