# Generated by Django 3.2 on 2024-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0007_rename_participant_id_selectedscheme_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedscheme',
            name='participant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
