# Generated by Django 5.0.7 on 2024-09-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0008_rename_cycle_no_round_cycle_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='cycle_id',
            new_name='cycle_no',
        ),
    ]
