# Generated by Django 3.2 on 2024-06-29 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0016_remove_scheme_code'),
        ('registrationadmin', '0008_auto_20240624_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.scheme'),
        ),
    ]
