# Generated by Django 3.2 on 2024-06-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0009_round_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylogunits',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Ready', 'Ready'), ('Open', 'Open'), ('Closed', 'Closed'), ('Report Available', 'Report Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Ready', 'Ready'), ('Open', 'Open'), ('Closed', 'Closed'), ('Report Available', 'Report Available')], max_length=50),
        ),
    ]
