# Generated by Django 5.0.7 on 2024-09-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0009_rename_cycle_id_round_cycle_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
