# Generated by Django 3.2 on 2024-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0010_auto_20240629_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='cycle_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
