# Generated by Django 4.1.3 on 2024-06-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountstatement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2baccountstatement',
            name='offered_test_id',
        ),
    ]
