# Generated by Django 5.0.7 on 2024-09-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountstatement', '0001_initial'),
        ('financeofficer', '0001_initial'),
        ('labowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='lab_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab'),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='lab_payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.labpayment', verbose_name='Lab Payment'),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='payment_in_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.paymentin', verbose_name='Payment In'),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='payment_out_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.paymentout', verbose_name='Payment Out'),
        ),
        migrations.AddField(
            model_name='b2baccountstatement',
            name='payment_out_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.paymentout', verbose_name='Payment In'),
        ),
        migrations.AddField(
            model_name='corporatelabstatement',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab ID'),
        ),
        migrations.AddField(
            model_name='donoraccountstatement',
            name='payment_in_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.paymentin', verbose_name='Payment In'),
        ),
    ]
