# Generated by Django 4.2.13 on 2024-07-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountstatement', '0002_accountstatement_lab_id_and_more'),
        ('accountstatement', '0002_initial'),
    ]

    operations = [
    ]
