# Generated by Django 4.2.13 on 2024-07-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountstatement', '0002_donoraccountstatement_payment_in_id'),
        ('accountstatement', '0002_initial'),
    ]

    operations = [
    ]
