# Generated by Django 4.2.13 on 2024-07-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountstatement', '0003_merge_20240707_2240'),
        ('accountstatement', '0004_accountstatement_lab_id_and_more'),
    ]

    operations = [
    ]
