# Generated by Django 3.2 on 2024-07-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_of_addition',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
