# Generated by Django 3.2 on 2024-05-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('b2b-admin', 'B2B Admin'), ('database-admin', 'Database Admin'), ('csr-admin', 'CSR Admin'), ('hr-admin', 'HR Admin'), ('finance-admin', 'Finance Admin'), ('auditor-admin', 'Auditor Admin'), ('registration-admin', 'Registration Admin'), ('database-admin', 'Database Admin'), ('CSR', 'CSR'), ('auditor', 'Auditor'), ('finance-officer', 'Finance Officer'), ('marketer-admin', 'Marketer Admin')], max_length=100, null=True),
        ),
    ]
