# Generated by Django 3.2 on 2024-07-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_date_of_addition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date_of_addition',
        ),
    ]
