# Generated by Django 3.2 on 2024-05-10 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('landline', models.CharField(blank=True, help_text='Please use the format: +922134552799', max_length=13, null=True)),
                ('added_by', models.CharField(max_length=255, null=True)),
                ('date_of_addition', models.DateTimeField(blank=True, default=datetime.datetime.now, max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Manufactural',
            },
        ),
    ]
