# Generated by Django 3.2 on 2024-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='organization name'),
        ),
    ]
