# Generated by Django 4.2.13 on 2024-07-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='membership_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Suspended', max_length=50),
        ),
        migrations.AddField(
            model_name='lab',
            name='payments_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50),
        ),
    ]
