# Generated by Django 3.2 on 2024-06-25 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_marketer_organization_id_staff_organization_id'),
        ('labowner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='done_by',
        ),
        migrations.AddField(
            model_name='lab',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
