# Generated by Django 3.2 on 2024-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
