# Generated by Django 4.2.13 on 2024-06-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='email_participant',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='fax',
            field=models.CharField(help_text='Please use the format: + (Country Code) (City Code without the leading zero) (fax number)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='landline',
            field=models.CharField(help_text='Please use the format: +922134552799', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='landline_registered_by',
            field=models.CharField(help_text='Please use the format: +922134552799', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='organization name'),
        ),
    ]
