# Generated by Django 4.2.13 on 2024-07-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0002_lab_membership_status_lab_payments_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='payments_status',
        ),
    ]
