# Generated by Django 3.2 on 2024-05-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0002_manufactural'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufactural',
            name='added_by',
        ),
    ]
