# Generated by Django 3.2 on 2024-07-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='landline_registered_by',
            field=models.CharField(help_text='Please use the format: +922134552799', max_length=30, null=True),
        ),
    ]
