# Generated by Django 4.1.3 on 2024-06-25 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0002_activitylogunits_cycle_activitylogunits_end_date_and_more'),
        ('organization', '0001_initial'),
        ('accountstatement', '0002_remove_b2baccountstatement_offered_test_id'),
        ('labowner', '0002_result_result_status_result_scheme_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Scheme added date')),
            ],
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='offered_test_id',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='Select_schemes',
        ),
        migrations.DeleteModel(
            name='OfferedTest',
        ),
        migrations.AddField(
            model_name='selectedscheme',
            name='lab_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab name'),
        ),
        migrations.AddField(
            model_name='selectedscheme',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='selectedscheme',
            name='scheme_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.scheme', verbose_name='Scheme name'),
        ),
    ]
