# Generated by Django 3.2 on 2024-07-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0003_alter_lab_landline_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
