# Generated by Django 5.0.7 on 2024-09-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0003_alter_lab_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='membership_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Suspended', max_length=50),
        ),
        migrations.AlterField(
            model_name='lab',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Accept', 'Accept'), ('Unapproved', 'Unapproved'), ('Cencel Request', 'Cencel Request'), ('Cencel', 'Cencel'), ('Org Suspended', 'Org Suspended')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='labcorporate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Accept', 'Accept'), ('Unapproved', 'Unapproved'), ('Cencel Request', 'Cencel Request'), ('Cencel', 'Cencel'), ('Org Suspended', 'Org Suspended')], default='Pending', max_length=50),
        ),
    ]
