# Generated by Django 4.2.13 on 2024-06-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0003_lab_organization_id_result_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='organization_id',
        ),
    ]
