# Generated by Django 4.2.13 on 2024-06-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0003_activitylog_organization_id_lab_organization_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='lab',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='landline_registered_by',
            field=models.CharField(help_text='Please use the format: +922134552799', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
