# Generated by Django 3.2 on 2024-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0003_remove_lab_payments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='result_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Accept', 'Accept'), ('Unapproved', 'Unapproved'), ('Cencel Request', 'Cencel Request'), ('Submited', 'Submited')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='result',
            name='rounds',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='scheme_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
