# Generated by Django 3.2 on 2024-06-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0003_lab_email_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='postalcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='fax',
            field=models.CharField(help_text='Please use the format: + (Country Code) (City Code without the leading zero) (fax number)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='landline',
            field=models.CharField(help_text='Please use the format: +922134552799', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='landline_registered_by',
            field=models.CharField(help_text='Please use the format: +922134552799', max_length=20, null=True),
        ),
    ]
