# Generated by Django 5.0.7 on 2024-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0004_alter_lab_membership_status_alter_lab_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='labpayment',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50),
        ),
    ]
