# Generated by Django 4.1.3 on 2024-05-24 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_staff_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labowner', '0004_remove_lab_select_schemes_remove_lab_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='Select_schemes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='account_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='address',
            field=models.CharField(help_text='Please enter your address to automatically locate it on map.', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='lab',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='done_at',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='Approved/Unapproved at'),
        ),
        migrations.AddField(
            model_name='lab',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Approved/Unapproved by'),
        ),
        migrations.AddField(
            model_name='lab',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='fax',
            field=models.CharField(help_text='Please use the format: + (Country Code) (City Code without the leading zero) (fax number)', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='financial_settlement',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Main Lab', 'Main Lab')], default='Self', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, null=True, verbose_name='Is lab active for the services?'),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_approved',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_blocked',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, null=True, verbose_name='Is lab blocked from using our services?'),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_temporary_blocked',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, null=True, verbose_name='Is lab temporary blocked from using our services?'),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lab Experience (Years)'),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_staff_designation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_staff_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registered by (Name)'),
        ),
        migrations.AddField(
            model_name='lab',
            name='landline',
            field=models.CharField(help_text='Please use the format: +922134552799', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='lab',
            name='marketer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.marketer', verbose_name='Marketer'),
        ),
        migrations.AddField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Lab name'),
        ),
        migrations.AddField(
            model_name='lab',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='phone',
            field=models.CharField(blank=True, help_text='Please use the format: +923123456789', max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='lab',
            name='postalcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='registered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='registered_by',
            field=models.CharField(choices=[('Lab', 'Lab'), ('Marketer', 'Marketer')], default='Lab', max_length=50),
        ),
        migrations.AddField(
            model_name='lab',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Accept', 'Accept'), ('Unapproved', 'Unapproved'), ('Cencel Request', 'Cencel Request'), ('Cencel', 'Cencel')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='lab',
            name='user_name',
            field=models.CharField(max_length=255, null=True, verbose_name='user name'),
        ),
    ]
