# Generated by Django 5.0.7 on 2024-09-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0005_remove_lab_payment_status_labpayment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labpayment',
            name='payment_status',
        ),
    ]
