# Generated by Django 5.0.7 on 2025-01-13 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True)),
                ('country', models.CharField(blank=True, choices=[('France', 'France'), ('London, UK', 'London, UK')], max_length=50, null=True)),
                ('currency', models.CharField(blank=True, choices=[('Afghani', 'Afghani'), ('Euro', 'Euro'), ('Dollar', 'Dollar'), ('Pakistani Rupees', 'Pakistani Rupees'), ('India Rupees', 'India Rupees'), ('Pound', 'Pound'), ('Dinar', 'Dinar'), ('Dirham', 'Dirham'), ('Japanese', 'Japanese')], max_length=50, null=True)),
                ('positiontaking', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bookie', models.CharField(blank=True, choices=[('Paradise', 'Paradise'), ('Betwar', 'Betwar')], max_length=50, null=True)),
                ('environment', models.CharField(blank=True, choices=[('Prod', 'Prod'), ('Dev', 'Dev')], max_length=50, null=True)),
                ('accountpolicy', models.CharField(blank=True, choices=[('BM Morning', 'BM Morning'), ('BM Evening', 'BM Evening')], max_length=50, null=True)),
                ('account_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
