# Generated by Django 5.0.7 on 2024-09-05 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, null=True, verbose_name='user name')),
                ('email', models.EmailField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('registered_at', models.DateTimeField(max_length=255, null=True)),
                ('photo', models.ImageField(default='blank', upload_to='organization', verbose_name="Organization's Photo")),
                ('account_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
