# Generated by Django 5.0.7 on 2024-09-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(blank=True, choices=[('Afghani', 'Afghani'), ('Euro', 'Euro'), ('Dollar', 'Dollar'), ('Pakistani Rupees', 'Pakistani Rupees'), ('India Rupees', 'India Rupees'), ('Pound', 'Pound'), ('Dinar', 'Dinar'), ('Dirham', 'Dirham'), ('Japanese', 'Japanese')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_proof',
            field=models.ImageField(default='blank', upload_to='organization', verbose_name="Organization's Photo"),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Block', 'Block')], default='Pending', max_length=50),
        ),
    ]
