# Generated by Django 5.0.7 on 2025-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(blank=True, choices=[('XAOS', 'XAOS'), ('BETWAR', 'BETWAR')], max_length=50, null=True)),
            ],
        ),
    ]
