# Generated by Django 5.0.7 on 2025-01-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0002_scrapdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapdata',
            name='affiliate_profit',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='figure',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='office_profit',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='office_profit_dropdown',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='partner_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='partner_profit',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='password',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='username',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='website_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
