# Generated by Django 5.0.7 on 2024-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0002_organization_amount_organization_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Block', 'Block'), ('Suspend', 'Suspend')], default='Pending', max_length=50),
        ),
    ]
