# Generated by Django 5.0.7 on 2025-01-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0003_scrapdata_affiliate_profit_scrapdata_figure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapdata',
            name='total',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
