# Generated by Django 5.0.7 on 2025-01-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0004_scrapdata_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapdata',
            name='total',
        ),
    ]
