# Generated by Django 5.0.7 on 2025-01-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0005_remove_scrapdata_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapdata',
            name='total',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
