# Generated by Django 5.0.7 on 2025-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0007_alter_scrapdata_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapdata',
            name='weekly',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
