# Generated by Django 5.0.7 on 2025-01-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0008_scrapdata_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapdata',
            name='user',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
