# Generated by Django 5.0.7 on 2025-01-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0010_scrapdata_partner_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapdata',
            name='partner_percentage',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
