# Generated by Django 3.2 on 2025-02-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0012_alter_scrapdata_partner_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapdata',
            name='volume',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
