# Generated by Django 3.2 on 2025-02-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0013_scrapdata_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapBetwarVolumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, choices=[('XAOS', 'XAOS'), ('BETWAR', 'BETWAR')], default='XAOS', max_length=50, null=True)),
                ('weak_date', models.CharField(blank=True, max_length=1000)),
                ('volume', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
