# Generated by Django 3.2 on 2025-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0015_alter_scrapbetwarvolumn_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbetwarvolumn',
            name='partner',
            field=models.CharField(blank=True, default='BETWAR', max_length=50, null=True),
        ),
    ]
