# Generated by Django 3.2 on 2025-02-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0016_scrapbetwarvolumn_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapdata',
            name='partner_percentage',
        ),
        migrations.AddField(
            model_name='scrapbetwarvolumn',
            name='partner_percentage',
            field=models.CharField(blank=True, default=0, max_length=1000),
        ),
    ]
