# Generated by Django 3.2 on 2025-02-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0017_auto_20250213_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbetwarvolumn',
            name='volume_formula',
            field=models.CharField(blank=True, default=0, max_length=1000),
        ),
    ]
