# Generated by Django 3.2 on 2025-02-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0018_scrapbetwarvolumn_volume_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBetwarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=1000)),
                ('volume_formula', models.CharField(blank=True, default=0, max_length=1000)),
                ('partner_percentage', models.CharField(blank=True, default=0, max_length=1000)),
                ('partner', models.CharField(blank=True, default='BETWAR', max_length=50, null=True)),
            ],
        ),
    ]
