# Generated by Django 3.2 on 2025-02-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizationdata', '0019_partnerbetwarinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapbetwarvolumn',
            name='partner_percentage',
        ),
        migrations.RemoveField(
            model_name='scrapbetwarvolumn',
            name='volume_formula',
        ),
    ]
