# Generated by Django 4.2.13 on 2024-06-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('databaseadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='added_by',
        ),
        migrations.AddField(
            model_name='analyte',
            name='allowed_units',
            field=models.ManyToManyField(related_name='allowed_units', to='databaseadmin.units'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='master_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_unit', to='databaseadmin.units'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='news',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='units',
            name='formula',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='analyte',
            name='reagent',
        ),
        migrations.AlterField(
            model_name='manufactural',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufactural',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyte',
            name='reagent',
            field=models.ManyToManyField(blank=True, related_name='analytes', to='databaseadmin.reagents'),
        ),
    ]
