# Generated by Django 4.2.13 on 2024-06-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyte',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseadmin.instrument'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseadmin.method'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseadmin.reagents'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseadmin.units'),
        ),
    ]
