# Generated by Django 4.2.13 on 2024-07-12 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databaseadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogunits',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='added by'),
        ),
    ]
