# Generated by Django 3.2 on 2024-07-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogunits',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='country',
        ),
        migrations.RemoveField(
            model_name='manufactural',
            name='country',
        ),
        migrations.RemoveField(
            model_name='reagents',
            name='country',
        ),
        migrations.AlterField(
            model_name='activitylogunits',
            name='type',
            field=models.CharField(choices=[('Units', 'Units'), ('Instruments', 'Instruments'), ('Reagent', 'Reagent'), ('Method', 'Method'), ('Manufactural', 'Manufactural'), ('Analyte', 'Analyte'), ('Instrumentlist', 'Instrumentlist'), ('City', 'City'), ('ParticipantProvince', 'ParticipantProvince'), ('District', 'District'), ('Department', 'Department'), ('Designation', 'Designation'), ('ParticipantType', 'ParticipantType'), ('ParticipantSector', 'ParticipantSector')], default='Units', max_length=50, verbose_name='Form type?'),
        ),
        migrations.DeleteModel(
            name='ParticipantCountry',
        ),
    ]
