# Generated by Django 3.2 on 2024-07-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='analytes',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Analyte'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
