# Generated by Django 5.0.7 on 2024-09-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='cycle',
            field=models.CharField(max_length=50),
        ),
    ]
