# Generated by Django 3.2 on 2024-06-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='added_by',
        ),
    ]
