# Generated by Django 3.2 on 2024-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='analytes',
        ),
        migrations.AddField(
            model_name='scheme',
            name='analytes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
