# Generated by Django 3.2 on 2024-06-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0002_remove_analyte_allowed_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyte',
            name='allowed_units',
            field=models.ManyToManyField(related_name='allowed_units', to='databaseadmin.Units'),
        ),
    ]
