# Generated by Django 3.2 on 2024-06-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0002_auto_20240611_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylogunits',
            old_name='organization',
            new_name='organization_id',
        ),
    ]
