# Generated by Django 3.2 on 2024-07-13 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databaseadmin', '0002_auto_20240711_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='details',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='scheme',
        ),
        migrations.AddField(
            model_name='sample',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='analytes',
            field=models.ManyToManyField(blank=True, related_name='samples', to='databaseadmin.Analyte'),
        ),
        migrations.AddField(
            model_name='sample',
            name='date_of_addition',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='detail',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='samplename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='scheme_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.scheme'),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Rounded', 'Rounded')], default='Created', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='account_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_account_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
