# Generated by Django 4.1.3 on 2024-06-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_address_organization_website_and_more'),
        ('databaseadmin', '0002_news_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogunits',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='analyte',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='manufactural',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='method',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='news',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='reagents',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='units',
            name='added_by',
        ),
        migrations.AddField(
            model_name='activitylogunits',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='manufactural',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='method',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='news',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='reagents',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='units',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
