# Generated by Django 3.2 on 2024-05-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
        migrations.AddField(
            model_name='manufactural',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Image'),
        ),
    ]
