# Generated by Django 5.0.7 on 2024-09-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0002_alter_cycle_cycle'),
        ('databaseadmin', '0002_auto_20240911_1632'),
    ]

    operations = [
    ]
