# Generated by Django 4.2.13 on 2024-07-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0002_analyte_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyte',
            name='type',
        ),
        migrations.AddField(
            model_name='analyte',
            name='analytetype',
            field=models.CharField(blank=True, choices=[('Quantitative', 'Quantitative'), ('Qualitative', 'Qualitative')], default='Quantitative', max_length=50),
        ),
    ]
