# Generated by Django 4.2.13 on 2024-06-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0002_instrument_activitylogunits_instrument_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='news_pictures/')),
                ('date_of_addition', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'News',
            },
        ),
        migrations.RemoveField(
            model_name='activitylogunits',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='analyte',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='manufactural',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='method',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='reagents',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='units',
            name='added_by',
        ),
    ]
