# Generated by Django 3.2 on 2024-07-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0002_activitylogunits_added_by'),
        ('databaseadmin', '0003_auto_20240712_2341'),
    ]

    operations = [
    ]
