# Generated by Django 4.2.13 on 2024-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0003_remove_analyte_reagent_analyte_reagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyte',
            name='reagent',
        ),
        migrations.AddField(
            model_name='analyte',
            name='reagents',
            field=models.ManyToManyField(blank=True, to='databaseadmin.reagents'),
        ),
    ]
