# Generated by Django 3.2 on 2024-06-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0003_rename_organization_activitylogunits_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogunits',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylogunits',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
