# Generated by Django 5.0.7 on 2024-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0003_merge_0002_alter_cycle_cycle_0002_auto_20240911_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='analytetype',
            field=models.CharField(blank=True, choices=[('Quantitative', 'Quantitative'), ('Qualitative', 'Qualitative')], default='Quantitative', max_length=50),
        ),
    ]
