# Generated by Django 4.2.13 on 2024-07-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationadmin', '0004_remove_round_scheme'),
        ('databaseadmin', '0003_sample_scheme_scheme_activitylogunits_scheme_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogunits',
            name='scheme_id',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='scheme_name',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='scheme',
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
    ]
