# Generated by Django 3.2 on 2024-06-29 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databaseadmin', '0003_analyte_allowed_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyte',
            name='allowed_units',
        ),
        migrations.RemoveField(
            model_name='analyte',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='analyte',
            name='method',
        ),
        migrations.RemoveField(
            model_name='analyte',
            name='unit',
        ),
        migrations.AddField(
            model_name='analyte',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Instrument'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='methods',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Method'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='units',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Units'),
        ),
        migrations.AddField(
            model_name='sample',
            name='account_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
