# Generated by Django 3.2 on 2024-06-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0004_news_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='staff_id',
        ),
    ]
