# Generated by Django 5.0.7 on 2024-09-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0004_scheme_analytetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
    ]
