# Generated by Django 5.0.7 on 2024-09-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0005_alter_scheme_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='analytetype',
            field=models.CharField(blank=True, choices=[('Quantitative', 'Quantitative'), ('Qualitative', 'Qualitative')], max_length=50),
        ),
    ]
