# Generated by Django 4.2.13 on 2024-07-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0005_sample_scheme_scheme_activitylogunits_scheme_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogunits',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='activitylogunits',
            name='cycle_id',
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
