# Generated by Django 4.2.13 on 2024-06-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0005_remove_analyte_instrument_remove_analyte_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyte',
            name='allowed_units',
        ),
    ]
