# Generated by Django 3.2 on 2024-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0005_auto_20240613_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='analytes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
