# Generated by Django 3.2 on 2024-06-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0005_remove_news_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyte',
            name='allowed_units',
        ),
    ]
