# Generated by Django 3.2 on 2024-07-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0006_remove_analyte_allowed_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyte',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='analyte',
            name='method',
        ),
        migrations.RemoveField(
            model_name='analyte',
            name='unit',
        ),
        migrations.AddField(
            model_name='analyte',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Instrument'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='methods',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Method'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='units',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Units'),
        ),
        migrations.AlterField(
            model_name='activitylogunits',
            name='type',
            field=models.CharField(choices=[('Units', 'Units'), ('Instruments', 'Instruments'), ('Reagent', 'Reagent'), ('Method', 'Method'), ('Manufactural', 'Manufactural'), ('Analyte', 'Analyte')], default='Units', max_length=50, verbose_name='Form type?'),
        ),
    ]
