# Generated by Django 3.2 on 2024-06-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0007_alter_activitylogunits_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='analytes',
        ),
    ]
