# Generated by Django 4.2.13 on 2024-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0007_remove_analyte_qualitativetype_units_qualitativetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='qualitativetype',
        ),
        migrations.AddField(
            model_name='analyte',
            name='qualitativetype',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Equivocal', 'Equivocal')], default='Positive', max_length=50),
        ),
    ]
