# Generated by Django 4.2.13 on 2024-06-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0007_alter_activitylogunits_type_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogunits',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.city'),
        ),
    ]
