# Generated by Django 4.2.13 on 2024-07-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0008_remove_units_qualitativetype_analyte_qualitativetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyte',
            name='qualitativetype',
        ),
    ]
