# Generated by Django 4.2.13 on 2024-07-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0009_activitylogunits_cycle_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogunits',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='activitylogunits',
            name='start_date',
        ),
    ]
