# Generated by Django 4.2.13 on 2024-07-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0010_remove_activitylogunits_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogunits',
            name='cycle',
        ),
    ]
