# Generated by Django 4.2.13 on 2024-07-01 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0010_alter_activitylogunits_type_designation_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogunits',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.department'),
        ),
        migrations.AddField(
            model_name='activitylogunits',
            name='designation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.designation'),
        ),
    ]
