# Generated by Django 4.2.13 on 2024-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0010_alter_activitylogunits_type_qualitativetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitativetype',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
