# Generated by Django 3.2 on 2024-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0010_remove_scheme_analytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='analytes',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Analyte'),
        ),
    ]
