# Generated by Django 4.2.13 on 2024-07-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0011_qualitativetype_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogunits',
            name='qualitativetype_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseadmin.qualitativetype'),
        ),
    ]
