# Generated by Django 4.2.13 on 2024-07-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0012_activitylogunits_qualitativetype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyte',
            name='qualitativetype',
            field=models.ManyToManyField(blank=True, to='databaseadmin.qualitativetype'),
        ),
    ]
