# Generated by Django 4.2.13 on 2024-07-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0012_alter_activitylogunits_type_participanttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='formula',
        ),
    ]
