# Generated by Django 3.2 on 2024-07-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0004_merge_20240713_1443'),
        ('databaseadmin', '0013_analyte_qualitativetype'),
    ]

    operations = [
    ]
