# Generated by Django 3.2 on 2024-06-26 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databaseadmin', '0014_auto_20240626_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='end_date',
            new_name='date_of_addition',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='analytes',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='cycle_no',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='rounds',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='scheme_name',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='start_date',
        ),
        migrations.AddField(
            model_name='scheme',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheme',
            name='code',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
