# Generated by Django 4.2.13 on 2024-07-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0015_instrument_country_instrument_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagents',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseadmin.participantcountry'),
        ),
        migrations.AddField(
            model_name='reagents',
            name='manufactural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseadmin.manufactural'),
        ),
    ]
