# Generated by Django 3.2 on 2024-06-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0015_auto_20240626_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='code',
        ),
    ]
