# Generated by Django 3.2 on 2024-06-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0016_remove_scheme_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='scheme_name',
            new_name='scheme',
        ),
    ]
