# Generated by Django 4.2.13 on 2024-07-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0016_reagents_country_reagents_manufactural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactural',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseadmin.participantcountry'),
        ),
    ]
