# Generated by Django 4.2.13 on 2024-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0017_alter_manufactural_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactural',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
