# Generated by Django 3.2 on 2024-06-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0018_rename_scheme_cycle_scheme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='cycle_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
