# Generated by Django 3.2 on 2024-06-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0019_alter_cycle_cycle_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='analytes',
        ),
    ]
