# Generated by Django 3.2 on 2024-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0020_remove_cycle_analytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='analytes',
            field=models.ManyToManyField(blank=True, to='databaseadmin.Analyte'),
        ),
    ]
