# Generated by Django 4.2.13 on 2024-07-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseadmin', '0020_alter_activitylogunits_type_alter_manufactural_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufactural',
            old_name='city',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='manufactural',
            name='address',
        ),
        migrations.RemoveField(
            model_name='manufactural',
            name='telephone',
        ),
    ]
