# Generated by Django 5.0.7 on 2024-09-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeofficer', '0001_initial'),
        ('labowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentin',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab'),
        ),
        migrations.AddField(
            model_name='activitylogfinance',
            name='payment_in_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.paymentin', verbose_name='Payment in id'),
        ),
        migrations.AddField(
            model_name='paymentout',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab'),
        ),
        migrations.AddField(
            model_name='activitylogfinance',
            name='payment_out_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.paymentout', verbose_name='Payment out id'),
        ),
    ]
