# Generated by Django 3.2 on 2024-07-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeofficer', '0001_initial'),
        ('labowner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentout',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab'),
        ),
        migrations.AddField(
            model_name='activitylogfinance',
            name='btd_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.banktransferdetail', verbose_name='BTD id'),
        ),
        migrations.AddField(
            model_name='activitylogfinance',
            name='invoice_adjustment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.invoiceadjustment', verbose_name='Invoice Adjustment id'),
        ),
        migrations.AddField(
            model_name='activitylogfinance',
            name='payment_in_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.paymentin', verbose_name='Payment in id'),
        ),
        migrations.AddField(
            model_name='activitylogfinance',
            name='payment_out_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeofficer.paymentout', verbose_name='Payment out id'),
        ),
        migrations.AddField(
            model_name='activitylogfinance',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Finance officer'),
        ),
    ]
