# Generated by Django 4.2.13 on 2024-07-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labowner', '0001_initial'),
        ('financeofficer', '0002_activitylogfinance_btd_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentin',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab'),
        ),
        migrations.AddField(
            model_name='paymentout',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labowner.lab', verbose_name='Lab'),
        ),
    ]
